### ISSUE TITLE
verification code is not coming

### ISSUE THREAD

**Issue by extamyy** [kirrishima/BlumAutoFarm#15]
10-20 18:47:17:9602 |  INFO   | Found 1 sessions.
10-20 18:47:17:9813 |  INFO   | ext | ♥ Program is running, please be patient ♥
A verification code has been sent via App
(ext) Verification code:

I'm from russia and my number starts with +7, but I don't get the code.
for example: I enter the number +79991234567

**Comment by kirrishima** [comment]
provide data from 'BlumBotData\TelegramSessions\ext WTelegram logs.txt' file for more info.

**Comment by extamyy** [comment]
--------------------------------------------------------------------------------------------------------------------------------
						2024-10-20 18:45:28.589 Bot Started
--------------------------------------------------------------------------------------------------------------------------------
2024-10-20 18:45:28.605 | Log Level: 1 | WTelegramClient 4.1.8+aef4fb795ad0da0b6e709114e07ee62283f8dbcc running under .NET 8.0.7
2024-10-20 18:45:28.626 | Log Level: 2 | Connecting to 149.154.167.50:443...
2024-10-20 18:45:28.707 | Log Level: 1 | Loaded a public key with fingerprint D09D1D85DE64FD85
2024-10-20 18:45:28.707 | Log Level: 1 | Loaded a public key with fingerprint B25898DF208D2603
2024-10-20 18:45:28.725 | Log Level: 1 | 0>Sending   ReqPqMulti...
2024-10-20 18:45:28.989 | Log Level: 1 | 0>Receiving ResPQ                                    2024-10-20 15:45:28Z clear
2024-10-20 18:45:28.992 | Log Level: 2 | Selected public key with fingerprint D09D1D85DE64FD85
2024-10-20 18:45:29.035 | Log Level: 1 | 0>Sending   ReqDHParams...
2024-10-20 18:45:29.759 | Log Level: 1 | 0>Receiving ServerDHParamsOk                         2024-10-20 15:45:29Z clear
2024-10-20 18:45:29.760 | Log Level: 2 | Verifying encryption key safety... (this should happen only once per DC)
2024-10-20 18:45:29.762 | Log Level: 1 | Time offset: -7597424 | Server: 15:45:29 UTC | Local: 15:45:29.7597424 UTC
2024-10-20 18:45:29.809 | Log Level: 1 | 0>Sending   SetClientDHParams...
2024-10-20 18:45:30.453 | Log Level: 1 | 0>Receiving DhGenOk                                  2024-10-20 15:45:30Z clear
2024-10-20 18:45:30.569 | Log Level: 1 | 0>Sending   InvokeWithLayer`1                        #48CD
2024-10-20 18:45:30.731 | Log Level: 1 | 0>Receiving MsgContainer                             2024-10-20 15:45:30Z (svc)
2024-10-20 18:45:30.732 | Log Level: 1 |             → NewSessionCreated                      2024-10-20 15:45:30Z  
2024-10-20 18:45:30.732 | Log Level: 1 |             → MsgsAck                                2024-10-20 15:45:30Z (svc) 
2024-10-20 18:45:30.841 | Log Level: 1 | 0>Receiving RpcResult                                2024-10-20 15:45:30Z
2024-10-20 18:45:30.858 | Log Level: 1 |              → Config                                #48CD
2024-10-20 18:45:30.867 | Log Level: 2 | Connected to DC 2... default_p2p_contacts, revoke_pm_inbox
2024-10-20 18:45:30.868 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:45:30Z (svc)
2024-10-20 18:45:30.869 | Log Level: 1 |             → Auth_SendCode                          #6CDE
2024-10-20 18:45:30.869 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:45:31.509 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:45:31Z
2024-10-20 18:45:31.509 | Log Level: 1 |              → Auth_SentCode                         #6CDE
2024-10-20 18:45:31.510 | Log Level: 3 | A verification code has been sent via App
2024-10-20 18:45:35.581 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:45:35Z (svc)
2024-10-20 18:45:35.581 | Log Level: 1 |             → GetFutureSalts                         #48AB
2024-10-20 18:45:35.581 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:45:35.739 | Log Level: 1 | 2>Receiving FutureSalts                              2024-10-20 15:45:35Z (svc) 
2024-10-20 18:46:30.574 | Log Level: 1 | 2>Sending   PingDelayDisconnect                      #C10A
2024-10-20 18:46:30.720 | Log Level: 1 | 2>Receiving Pong                                     2024-10-20 15:46:30Z (svc) 
--------------------------------------------------------------------------------------------------------------------------------
						2024-10-20 18:47:18.358 Bot Started
--------------------------------------------------------------------------------------------------------------------------------
2024-10-20 18:47:18.385 | Log Level: 2 | Loaded previous session
2024-10-20 18:47:18.387 | Log Level: 1 | WTelegramClient 4.1.8+aef4fb795ad0da0b6e709114e07ee62283f8dbcc running under .NET 8.0.7
2024-10-20 18:47:18.400 | Log Level: 2 | Connecting to 149.154.167.50:443...
2024-10-20 18:47:18.483 | Log Level: 1 | 2>Sending   InvokeWithLayer`1                        #AC42
2024-10-20 18:47:18.732 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:47:18Z
2024-10-20 18:47:18.773 | Log Level: 1 |              → Config                                #AC42
2024-10-20 18:47:18.776 | Log Level: 2 | Connected to DC 2... default_p2p_contacts, revoke_pm_inbox
2024-10-20 18:47:18.777 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:47:18Z (svc)
2024-10-20 18:47:18.777 | Log Level: 1 |             → Auth_SendCode                          #468A
2024-10-20 18:47:18.777 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:47:18.935 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:47:18Z
2024-10-20 18:47:18.935 | Log Level: 1 |              → Auth_SentCode                         #468A
2024-10-20 18:47:18.936 | Log Level: 3 | A verification code has been sent via App
--------------------------------------------------------------------------------------------------------------------------------
						2024-10-20 18:48:37.422 Bot Started
--------------------------------------------------------------------------------------------------------------------------------
2024-10-20 18:48:37.431 | Log Level: 1 | WTelegramClient 4.1.8+aef4fb795ad0da0b6e709114e07ee62283f8dbcc running under .NET 8.0.7
2024-10-20 18:48:37.444 | Log Level: 2 | Connecting to 149.154.167.50:443...
2024-10-20 18:48:37.572 | Log Level: 1 | Loaded a public key with fingerprint D09D1D85DE64FD85
2024-10-20 18:48:37.572 | Log Level: 1 | Loaded a public key with fingerprint B25898DF208D2603
2024-10-20 18:48:37.589 | Log Level: 1 | 0>Sending   ReqPqMulti...
2024-10-20 18:48:38.106 | Log Level: 1 | 0>Receiving ResPQ                                    2024-10-20 15:48:37Z clear
2024-10-20 18:48:38.108 | Log Level: 2 | Selected public key with fingerprint D09D1D85DE64FD85
2024-10-20 18:48:38.141 | Log Level: 1 | 0>Sending   ReqDHParams...
2024-10-20 18:48:38.729 | Log Level: 1 | 0>Receiving ServerDHParamsOk                         2024-10-20 15:48:38Z clear
2024-10-20 18:48:38.730 | Log Level: 2 | Verifying encryption key safety... (this should happen only once per DC)
2024-10-20 18:48:38.732 | Log Level: 1 | Time offset: -7293186 | Server: 15:48:38 UTC | Local: 15:48:38.7293186 UTC
2024-10-20 18:48:38.776 | Log Level: 1 | 0>Sending   SetClientDHParams...
2024-10-20 18:48:39.365 | Log Level: 1 | 0>Receiving DhGenOk                                  2024-10-20 15:48:39Z clear
2024-10-20 18:48:39.481 | Log Level: 1 | 0>Sending   InvokeWithLayer`1                        #2216
2024-10-20 18:48:39.664 | Log Level: 1 | 0>Receiving MsgContainer                             2024-10-20 15:48:39Z (svc)
2024-10-20 18:48:39.665 | Log Level: 1 |             → NewSessionCreated                      2024-10-20 15:48:39Z  
2024-10-20 18:48:39.665 | Log Level: 1 |             → MsgsAck                                2024-10-20 15:48:39Z (svc) 
2024-10-20 18:48:39.978 | Log Level: 1 | 0>Receiving RpcResult                                2024-10-20 15:48:39Z
2024-10-20 18:48:39.981 | Log Level: 1 |              → Config                                #2216
2024-10-20 18:48:39.988 | Log Level: 2 | Connected to DC 2... default_p2p_contacts, revoke_pm_inbox
2024-10-20 18:48:39.989 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:48:39Z (svc)
2024-10-20 18:48:39.990 | Log Level: 1 |             → Auth_SendCode                          #3E0F
2024-10-20 18:48:39.990 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:48:40.313 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:48:40Z
2024-10-20 18:48:40.313 | Log Level: 1 |              → Auth_SentCode                         #3E0F
2024-10-20 18:48:40.313 | Log Level: 3 | A verification code has been sent via App
2024-10-20 18:48:44.485 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:48:44Z (svc)
2024-10-20 18:48:44.485 | Log Level: 1 |             → GetFutureSalts                         #E870
2024-10-20 18:48:44.485 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:48:44.649 | Log Level: 1 | 2>Receiving FutureSalts                              2024-10-20 15:48:44Z (svc) 
2024-10-20 18:49:39.478 | Log Level: 1 | 2>Sending   PingDelayDisconnect                      #934F
2024-10-20 18:49:39.648 | Log Level: 1 | 2>Receiving Pong                                     2024-10-20 15:49:39Z (svc) 
2024-10-20 18:50:18.032 | Log Level: 1 | 2>Sending   Auth_SignIn                              #C0F5
2024-10-20 18:50:18.423 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:50:18Z
2024-10-20 18:50:18.423 | Log Level: 4 |              → RpcError 400 PHONE_CODE_INVALID       #C0F5
2024-10-20 18:50:18.424 | Log Level: 4 | Wrong verification code!
2024-10-20 18:50:23.520 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:50:23Z (svc)
2024-10-20 18:50:23.520 | Log Level: 1 |             → Auth_SignIn                            #587F
2024-10-20 18:50:23.520 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:50:23.676 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:50:23Z
2024-10-20 18:50:23.676 | Log Level: 4 |              → RpcError 400 PHONE_CODE_INVALID       #587F
2024-10-20 18:50:23.677 | Log Level: 4 | Wrong verification code!
2024-10-20 18:50:39.662 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:50:39Z (svc)
2024-10-20 18:50:39.662 | Log Level: 1 |             → PingDelayDisconnect                    #165B
2024-10-20 18:50:39.662 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:50:39.834 | Log Level: 1 | 2>Receiving Pong                                     2024-10-20 15:50:39Z (svc) 
--------------------------------------------------------------------------------------------------------------------------------
						2024-10-20 18:51:23.771 Bot Started
--------------------------------------------------------------------------------------------------------------------------------
2024-10-20 18:51:23.780 | Log Level: 1 | WTelegramClient 4.1.8+aef4fb795ad0da0b6e709114e07ee62283f8dbcc running under .NET 8.0.7
2024-10-20 18:51:23.793 | Log Level: 2 | Connecting to 149.154.167.50:443...
2024-10-20 18:51:26.912 | Log Level: 1 | Loaded a public key with fingerprint D09D1D85DE64FD85
2024-10-20 18:51:26.912 | Log Level: 1 | Loaded a public key with fingerprint B25898DF208D2603
2024-10-20 18:51:26.929 | Log Level: 1 | 0>Sending   ReqPqMulti...
2024-10-20 18:51:27.501 | Log Level: 1 | 0>Receiving ResPQ                                    2024-10-20 15:51:27Z clear
2024-10-20 18:51:27.504 | Log Level: 2 | Selected public key with fingerprint D09D1D85DE64FD85
2024-10-20 18:51:27.577 | Log Level: 1 | 0>Sending   ReqDHParams...
2024-10-20 18:51:28.185 | Log Level: 1 | 0>Receiving ServerDHParamsOk                         2024-10-20 15:51:27Z clear
2024-10-20 18:51:28.186 | Log Level: 2 | Verifying encryption key safety... (this should happen only once per DC)
2024-10-20 18:51:28.188 | Log Level: 1 | Time offset: -11853909 | Server: 15:51:27 UTC | Local: 15:51:28.1853909 UTC
2024-10-20 18:51:28.235 | Log Level: 1 | 0>Sending   SetClientDHParams...
2024-10-20 18:51:28.926 | Log Level: 1 | 0>Receiving DhGenOk                                  2024-10-20 15:51:29Z clear
2024-10-20 18:51:29.043 | Log Level: 1 | 0>Sending   InvokeWithLayer`1                        #047B
2024-10-20 18:51:29.233 | Log Level: 1 | 0>Receiving MsgContainer                             2024-10-20 15:51:30Z (svc)
2024-10-20 18:51:29.234 | Log Level: 1 |             → NewSessionCreated                      2024-10-20 15:51:29Z  
2024-10-20 18:51:29.234 | Log Level: 1 |             → MsgsAck                                2024-10-20 15:51:29Z (svc) 
2024-10-20 18:51:29.391 | Log Level: 1 | 0>Receiving RpcResult                                2024-10-20 15:51:29Z
2024-10-20 18:51:29.394 | Log Level: 1 |              → Config                                #047B
2024-10-20 18:51:29.402 | Log Level: 2 | Connected to DC 2... default_p2p_contacts, revoke_pm_inbox
2024-10-20 18:51:29.403 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:51:29Z (svc)
2024-10-20 18:51:29.404 | Log Level: 1 |             → Auth_SendCode                          #250D
2024-10-20 18:51:29.404 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:51:29.697 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:51:29Z
2024-10-20 18:51:29.698 | Log Level: 4 |              → RpcError 400 PHONE_NUMBER_INVALID     #250D
--------------------------------------------------------------------------------------------------------------------------------
						2024-10-20 18:51:51.752 Bot Started
--------------------------------------------------------------------------------------------------------------------------------
2024-10-20 18:51:51.780 | Log Level: 2 | Loaded previous session
2024-10-20 18:51:51.782 | Log Level: 1 | WTelegramClient 4.1.8+aef4fb795ad0da0b6e709114e07ee62283f8dbcc running under .NET 8.0.7
2024-10-20 18:51:51.795 | Log Level: 2 | Connecting to 149.154.167.41:443...
2024-10-20 18:51:51.903 | Log Level: 1 | 2>Sending   InvokeWithLayer`1                        #2317
2024-10-20 18:51:52.153 | Log Level: 1 | 2>Receiving MsgContainer                             2024-10-20 15:51:52Z (svc)
2024-10-20 18:51:52.154 | Log Level: 1 |             → RpcResult                              2024-10-20 15:51:29Z
2024-10-20 18:51:52.191 | Log Level: 1 |              → RpcError                              for past msgId #250D
2024-10-20 18:51:52.191 | Log Level: 1 |             → MsgsAck                                2024-10-20 15:51:52Z (svc) 
2024-10-20 18:51:52.286 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:51:52Z
2024-10-20 18:51:52.288 | Log Level: 1 |              → Config                                #2317
2024-10-20 18:51:52.291 | Log Level: 2 | Connected to DC 2... default_p2p_contacts, revoke_pm_inbox
2024-10-20 18:51:52.293 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:51:52Z (svc)
2024-10-20 18:51:52.293 | Log Level: 1 |             → Auth_SendCode                          #52B4
2024-10-20 18:51:52.293 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:51:52.545 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:51:52Z
2024-10-20 18:51:52.545 | Log Level: 4 |              → RpcError 400 PHONE_NUMBER_INVALID     #52B4
--------------------------------------------------------------------------------------------------------------------------------
						2024-10-20 18:52:41.799 Bot Started
--------------------------------------------------------------------------------------------------------------------------------
2024-10-20 18:52:41.808 | Log Level: 1 | WTelegramClient 4.1.8+aef4fb795ad0da0b6e709114e07ee62283f8dbcc running under .NET 8.0.7
2024-10-20 18:52:41.821 | Log Level: 2 | Connecting to 149.154.167.50:443...
2024-10-20 18:52:42.914 | Log Level: 1 | Loaded a public key with fingerprint D09D1D85DE64FD85
2024-10-20 18:52:42.914 | Log Level: 1 | Loaded a public key with fingerprint B25898DF208D2603
2024-10-20 18:52:42.932 | Log Level: 1 | 0>Sending   ReqPqMulti...
2024-10-20 18:52:43.225 | Log Level: 1 | 0>Receiving ResPQ                                    2024-10-20 15:52:43Z clear
2024-10-20 18:52:43.227 | Log Level: 2 | Selected public key with fingerprint D09D1D85DE64FD85
2024-10-20 18:52:43.273 | Log Level: 1 | 0>Sending   ReqDHParams...
2024-10-20 18:52:43.967 | Log Level: 1 | 0>Receiving ServerDHParamsOk                         2024-10-20 15:52:43Z clear
2024-10-20 18:52:43.968 | Log Level: 2 | Verifying encryption key safety... (this should happen only once per DC)
2024-10-20 18:52:43.970 | Log Level: 1 | Time offset: -9675830 | Server: 15:52:43 UTC | Local: 15:52:43.9675830 UTC
2024-10-20 18:52:44.016 | Log Level: 1 | 0>Sending   SetClientDHParams...
2024-10-20 18:52:44.813 | Log Level: 1 | 0>Receiving DhGenOk                                  2024-10-20 15:52:44Z clear
2024-10-20 18:52:44.936 | Log Level: 1 | 0>Sending   InvokeWithLayer`1                        #A010
2024-10-20 18:52:45.082 | Log Level: 1 | 0>Receiving MsgContainer                             2024-10-20 15:52:45Z (svc)
2024-10-20 18:52:45.083 | Log Level: 1 |             → NewSessionCreated                      2024-10-20 15:52:45Z  
2024-10-20 18:52:45.084 | Log Level: 1 |             → MsgsAck                                2024-10-20 15:52:45Z (svc) 
2024-10-20 18:52:45.198 | Log Level: 1 | 0>Receiving RpcResult                                2024-10-20 15:52:45Z
2024-10-20 18:52:45.201 | Log Level: 1 |              → Config                                #A010
2024-10-20 18:52:45.208 | Log Level: 2 | Connected to DC 2... default_p2p_contacts, revoke_pm_inbox
2024-10-20 18:52:45.210 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:52:45Z (svc)
2024-10-20 18:52:45.210 | Log Level: 1 |             → Auth_SendCode                          #9985
2024-10-20 18:52:45.210 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:52:45.436 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:52:45Z
2024-10-20 18:52:45.436 | Log Level: 1 |              → Auth_SentCode                         #9985
2024-10-20 18:52:45.436 | Log Level: 3 | A verification code has been sent via App
2024-10-20 18:52:49.942 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:52:49Z (svc)
2024-10-20 18:52:49.942 | Log Level: 1 |             → GetFutureSalts                         #968D
2024-10-20 18:52:49.942 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:52:50.115 | Log Level: 1 | 2>Receiving FutureSalts                              2024-10-20 15:52:50Z (svc) 
2024-10-20 18:53:44.939 | Log Level: 1 | 2>Sending   PingDelayDisconnect                      #7BC4
2024-10-20 18:53:45.424 | Log Level: 1 | 2>Receiving Pong                                     2024-10-20 15:53:45Z (svc) 
2024-10-20 18:53:59.908 | Log Level: 5 | 2>An exception occured in the reactor: System.IO.IOException: Unable to read data from the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение..
 ---> System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at WTelegram.Helpers.FullReadAsync(Stream stream, Byte[] buffer, Int32 length, CancellationToken ct)
   at WTelegram.Client.Reactor(Stream stream, CancellationTokenSource cts)
2024-10-20 18:54:05.980 | Log Level: 2 | Connecting to 149.154.167.50:443...
2024-10-20 18:55:06.056 | Log Level: 1 | 2>Sending   PingDelayDisconnect                      #26E6
2024-10-20 18:55:06.124 | Log Level: 1 | 2>Receiving Pong                                     2024-10-20 15:55:06Z (svc) 
--------------------------------------------------------------------------------------------------------------------------------
						2024-10-20 18:56:01.362 Bot Started
--------------------------------------------------------------------------------------------------------------------------------
2024-10-20 18:56:01.395 | Log Level: 2 | Loaded previous session
2024-10-20 18:56:01.398 | Log Level: 1 | WTelegramClient 4.1.8+aef4fb795ad0da0b6e709114e07ee62283f8dbcc running under .NET 8.0.7
2024-10-20 18:56:01.411 | Log Level: 2 | Connecting to 149.154.167.50:443...
2024-10-20 18:56:01.505 | Log Level: 1 | 2>Sending   InvokeWithLayer`1                        #85D1
2024-10-20 18:56:01.661 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:56:01Z
2024-10-20 18:56:01.711 | Log Level: 1 |              → Config                                #85D1
2024-10-20 18:56:01.713 | Log Level: 2 | Connected to DC 2... default_p2p_contacts, revoke_pm_inbox
2024-10-20 18:56:01.715 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:56:01Z (svc)
2024-10-20 18:56:01.715 | Log Level: 1 |             → Auth_SendCode                          #85D5
2024-10-20 18:56:01.715 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:56:01.795 | Log Level: 1 | 2>Receiving RpcResult                                2024-10-20 15:56:01Z
2024-10-20 18:56:01.795 | Log Level: 1 |              → Auth_SentCode                         #85D5
2024-10-20 18:56:01.795 | Log Level: 3 | A verification code has been sent via App
2024-10-20 18:57:01.505 | Log Level: 1 | 2>Sending   MsgContainer                             2024-10-20 15:57:00Z (svc)
2024-10-20 18:57:01.505 | Log Level: 1 |             → PingDelayDisconnect                    #AE9C
2024-10-20 18:57:01.505 | Log Level: 1 |             → MsgsAck                               
2024-10-20 18:57:01.570 | Log Level: 1 | 2>Receiving Pong                                     2024-10-20 15:57:01Z (svc) 
2024-10-20 18:58:01.620 | Log Level: 1 | 2>Sending   PingDelayDisconnect                      #5E75
2024-10-20 18:58:01.685 | Log Level: 1 | 2>Receiving Pong                                     2024-10-20 15:58:01Z (svc) 
2024-10-20 18:59:01.686 | Log Level: 1 | 2>Sending   PingDelayDisconnect                      #FBB1
2024-10-20 18:59:01.750 | Log Level: 1 | 2>Receiving Pong                                     2024-10-20 15:59:01Z (svc)

**Comment by extamyy** [comment]
I still haven't received the verification code

**Comment by kirrishima** [comment]
according to the logs, the confirmation code was successfully sent. if it has not arrived, it may be due to problems accessing the telegram servers on your side. The problem is not related to the operation of this application, make sure that you entered the phone number from your EXISTING telegram account correctly, check the correctness of api_id and api_hashand try to wait longer. Also, consider using VPN

**Comment by kirrishima** [comment]
there is also some errors telling you had entered incorrect phone number: 2024-10-20 18:51:29.698 | Log Level: 4 | → RpcError 400 PHONE_NUMBER_INVALID #250D

**Comment by extamyy** [comment]
yes, i know about incorrect phone number, i just tested

**Comment by extamyy** [comment]
about api id and api hash I entered correctly, but I used GoodByeDPI and Amnezia, now I will try without it all

**Comment by kirrishima** [comment]
also keep in mind that telegram can send this codes up to 20 minutes

**Comment by extamyy** [comment]
ok thank you, but I still haven't received the verification code

**Comment by extamyy** [comment]
I was able to start the game, it says “Starting the game. Passes to be used: 7.”, what does passes mean?

**Comment by kirrishima** [comment]
tickets used in the drop game
![image](https://github.com/user-attachments/assets/672b91be-a91a-4f67-894d-4ebcd91712b0)
you can change this amount in the settings file.json is the same as the reward point's range

**Comment by extamyy** [comment]
![image](https://github.com/user-attachments/assets/8d9dae9a-ef26-46d2-8876-a5535bf60fc0)

how can I take away the sleep?

**Comment by kirrishima** [comment]
what do you even mean? sleep is a delay before farm is ended

**Comment by extamyy** [comment]
Yeah, I mean, how do I fix the 8-hour delay?

**Comment by kirrishima** [comment]
u can't, it's blum bot's limit for farming duration

**Comment by extamyy** [comment]
ok thank you, u can close ticket

**Comment by kirrishima** [comment]
спасиба
